polls/football/urls.py
from django.conf.urls import url

from . import views

app_name = 'football'

urlpatterns = [

    # url(r'^$',views.index, name='index'),
    # url(r'^(?P<question_id>[0-9]+)/$',views.detail, name='detail'),
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote')

    url(r'^$',views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),



]

polls/polls/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^football/',include('football.urls')),
    url(r'^',include('football.urls'))
]

polls/football/models.py
from django.db import models
# Create your models here.
from django.utils import  timezone
import  datetime


class Question (models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    # def published_date(self):
    #
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def published_date(self):
        now = timezone.now()
        return now-datetime.timedelta(days=1) < self.pub_date <=now
    published_date.admin_order_field = 'pub_date'
    published_date.boolean = True
    published_date.short_description = "Published Recently??"


class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/football/views.py
from django.shortcuts import render,get_object_or_404,render_to_response
from django.template import loader
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.db.models import Sum

# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from .models import Question,Choice

# def index(request):
#
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # output = ",".join([q.question_text for q in latest_question_list])
#     #
#     template = loader.get_template('football/index.html')
#     #
#     context = {'latest_question_list':latest_question_list,}
#     #
#     # # return HttpResponse(template.render(context,request))
#     # # return render(request,"football/index.html",context)
#     # return HttpResponse(output)
#
#     return HttpResponse(template.render(context, request))
#
#
# def detail(request,question_id):
#
#     question = get_object_or_404(Question, pk=question_id)
#     # return HttpResponse('Your are looking at question %s.' %question_id)
#     return render(request, 'football/detail.html',{'question':question})
#
# def result(request,question_id):
#
#     # return HttpResponse('Resulst')
#     question = get_object_or_404(Question,pk=question_id)
#
#     return render(request, 'football/results.html',{'question':question})

class IndexView(generic.ListView):

    template_name = "football/index.html"
    context_object_name = 'latest_question_list'

    # def get_queryset(self):
    #     return Question.objects.order_by('-pub_date')[:5]

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()

        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'football/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question

    template_name = 'football/results.html'

    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)

        context['total_votes'] = context['object'].choice_set.aggregate(Sum('votes')).values()[0]


        return context



def vote(request,question_id):
    # return HttpResponse("Votes")

    question  = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):

        return render(request, 'football/detail.html',{
            'question' : question,
            'error_message': 'You didn"t select a choice',
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('football:results',args=(question.id,)))

polls/football/templates/football/detail.html
{% extends 'football/master.html' %}


{% block title %} {{ question.question_text }} {% endblock %}

{% block content %}
        <div class="alert alert-info">

<h3>
{% if question %}{{ question.question_text }} {% endif %}
</h3>
        </div>

{% if error_message %}
    <div class="alert alert-danger">
  <strong>Danger!</strong> {{ error_message  }}.
</div>
 {% endif %}
    <div class="">
<form class="" action="{% url 'football:vote' question.id%}" method="post" role="form" style="background-color: whitesmoke;padding-left: 100px">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice-{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice-{{ forloop.counter}}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input class="btn btn-success btn-sm" type="submit" value="Vote"/>
</form>
    </div>
{% endblock %}

polls/football/templates/football/index.html
{% extends 'football/master.html' %}


{% block title %} Football Polling {% endblock %}


{% block content %}
    <div class="alert alert-info">
    <h1> Latest Polls </h1>
</div>
    {% if latest_question_list %}
        <div>
    <table class="table table-hover table-striped table-responsive">

     <tr class="success">
            <th>Poll Title</th>
            <th>Published Date</th>
        </tr>
            {% for question in latest_question_list %}
                    <tr style="background-color:whitesmoke">

                <td><a href="{% url 'football:detail' question.id %}">{{ question.question_text }}</a></td>
                        <td>{{ question.pub_date }}</td>
                    </tr>

            {% endfor %}
        </table>
        </div>
    {% else %}
        <p>No Football Polls are available.</p>
    {% endif %}

{% endblock %}

polls/football/templates/football/master.html
{% load staticfiles %}
{% load mathfilters %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
{#    <link rel="stylesheet" href="{% static 'football/bootstrap/css/bootstrap.min.css' %}">#}

    {#    <link rel="stylesheet" href="{% static 'football/bootstrap/css/bootstrap.css' %}">#}
        <link rel="stylesheet" href="{% static 'football/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Poll Station</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'football:index' %}">Home</a></li>
                <li><a href="{% url 'football:index' %}">All Polls</a></li>
                 <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Category <span
                        class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'football:index' %}">Football</a></li>
                        <li><a href="#">Cricket</a></li>
                        <li><a href="#">Politics</a></li>
                    </ul>
                </li>

            </ul>

        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container" style="padding-top: 100px">

    {% block content %}
        dsfdssdfs
    {% endblock %}
</div> <!-- /container -->


</body>
</html>

polls/football/templates/football/results.html
{% extends 'football/master.html' %}
{% load mathfilters %}


{% block title %} {{ question.question_text }} {% endblock %}

{% block content %}
        <div class="alert alert-info">

    <h1>{{ question.question_text }}</h1>
</div>
    <a href="{% url 'football:detail' question.id %}" class="btn btn-sm btn-primary pull-right">Vote Again << </a>
    <table class="table table-hover table-striped table-responsive">
        <tr class="success">
            <th>Club</th>
            <th>Votes</th>
            <th>Percentage</th>
        </tr>
        {% for choice in question.choice_set.all %}
            <tr style="background-color: whitesmoke">
                <td class="club">{{ choice.choice_text }}</td>
                <td class="vote">{{ choice.votes }}</td>
                {% with numerator=choice.votes|mul:100 denominator=total_votes %}
                    <td>{{ numerator|div:denominator }} %</td>
                {% endwith %}

            </tr>
        {% endfor %}
    </table>

    <script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>


    <script type="text/javascript">

        $(document).ready(function () {

            var clubs = [];
            var votes = [];
            $('.club').each(function(i) {

                 console.log( i + ": " + $( this ).text() );
                clubs.push($(this).text());
            });
            $('.vote').each(function (i) {
                console.log( i + ": " + $( this ).text() );
                votes.push(parseInt($(this).text()));


            });

            var data = {
                labels: clubs,
                datasets: [
                    {
                        label: 'dsfs',
                        fill: false,
                        lineTension: 0.1,
                        backgroundColor: "rgba(75,192,192,0.4)",
                        borderColor: "rgba(75,192,192,1)",
                        borderCapStyle: 'butt',
                        borderDash: [],
                        borderDashOffset: 0.0,
                        borderJoinStyle: 'miter',
                        pointBorderColor: "rgba(75,192,192,1)",
                        pointBackgroundColor: "#fff",
                        pointBorderWidth: 1,
                        pointHoverRadius: 5,
                        pointHoverBackgroundColor: "rgba(75,192,192,1)",
                        pointHoverBorderColor: "rgba(220,220,220,1)",
                        pointHoverBorderWidth: 2,
                        pointRadius: 1,
                        pointHitRadius: 10,
                        data: votes,
                        spanGaps: false,
                    }
                ]
            };
            var ctx = document.getElementById("myChart").getContext("2d");
            var myLineChart = new Chart(ctx).Bar(data);
        });
    </script>


    <div>
    <h3 class="alert alert-info"> Bar Graph </h3>
    <canvas id="myChart" width="600" height="200"></canvas>
    </div>

{% endblock %}